### PR TITLE
Added new command-line options for creating a new issue.

### PR DESCRIPTION
**Pull request by bprinty**
Added:
--assignee
--reporter

The JIRA instance I'm using requires those for new issues, and I couldn't figure out a way to pass those in to jira-cli.

### CODE REVIEW

**Comment by alisaifee** [comment]
Thanks @bprinty. I no longer have access to a jira instance that I control, so I'm unable to test out the implementation (though it looks fine to me). Could you help me verify the following behaviour:
* arguments `--assignee` and `--reporter` not passed in
* only one of `--assignee` or `--reporter` passed in
* both passed in

and that the resulting ticket has the appropriate values set.

**Comment by bprinty** [comment]
Sure thing! See below:
<br /><br />

##### Arguments ```--assignee``` and ```--reporter``` not passed in:

___Note___: this is the same behaviour I was getting before making the change. My JIRA instance doesn't let me create issues without an assignee. But, since the same result is returned, the request must be the same.
```bash 
~$ jira-cli new --project TEST 'This is a test issue.'
{assignee=Issues must be assigned.} : []
```

##### Only one of ```--assignee``` or ```--reporter``` passed in:

___Note___: when reporter is not specified, the default for JIRA is to make the assignee the reporter. That's why both are filled in below. When only ```--reporter``` is specified, I get the same behavior as before (because my JIRA doesn't let me create issues without an assignee). But, since the same result is returned, the request must be the same.
```bash 
~$ jira-cli new --assignee bprinty --project TEST 'This is a second test issue.'
status               : Open
reporter             : bprinty
summary              : This is a second test issue.
assignee             : bprinty
link                 : http://localhost:8080/browse/TEST-5
issue                : TEST-5
~$ jira-cli new --reporter bprinty --project TEST 'This is a third test issue.'
{assignee=Issues must be assigned.} : []
```

##### Both ```--assignee``` and ```--reporter``` passed in:

```bash
~$ jira-cli new --reporter normsbee --assignee bprinty --project TEST 'This is a fourth test issue.'
status               : Open
reporter             : normsbee
summary              : This is a fourth test issue.
assignee             : bprinty
link                 : http://localhost:8080/browse/TEST-6
issue                : TEST-6
```

**Comment by alisaifee** [comment]
brilliant, thank you very much.

**Comment by alisaifee** [comment]
released in `2.0.6`

**Comment by bprinty** [comment]
No problemo. Thanks for this awesome piece of software!

**Comment by alisaifee** [comment]
@bprinty I had to make some modifications to the --assignee / --reporter flows to work with the rest api. Have released a new version `2.0.8`. If you could please check and make sure I haven't broken your requirements.

**Comment by bprinty** [comment]
@alisaifee It's working on my side:

```bash
~$ jira-cli new --reporter normsbee --assignee bprinty --project TEST 'This is another test issue.'
status               : Open
reporter             : normsbee
summary              : This is another test issue.
assignee             : bprinty
link                 : http://localhost:8080/browse/TEST-7
issue                : TEST-7
```

Thanks for the heads up!

**Pull request merged**
